apiVersion: v1
kind: Namespace
metadata:
  name: juice-shop-wazuh-included
---
apiVersion: v1
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: juice-shop-wazuh-included
data:
  authd.pass: cGFzc3dvcmQ= # string "password" base64 encoded
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-juice-shop-wazuh-included-storage
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  dataLocality: best-effort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: juice-shop-wazuh-agent
  namespace: juice-shop-wazuh-included
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juice-shop-wazuh-agent
  template:
    metadata:
      labels:
        app: juice-shop-wazuh-agent
    spec:
      hostname: juice-shop-wazuh-agent
      containers:
        - name: wazuh-agent
          image: matteodalgrande/juice-shop-wazuh-agent-included:1.0.4
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: true
            capabilities:
              add: ["SETGID", "SETUID"]
          volumeMounts:
            - name: wazuh-authd-pass
              mountPath: /var/ossec/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: application-data
              mountPath: /application/
              readOnly: false
            - name: wazuh-agent-data
              mountPath: /var/ossec
              readOnly: false
      volumes:
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
  volumeClaimTemplates:
  - metadata:
      name: wazuh-agent-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn-wazuh-agent-storage"
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: application-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "longhorn-wazuh-agent-storage"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: juice-shop-wazuh-included
spec:
  selector:
    app: juice-shop-wazuh-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30011
  type: NodePort
